name: risk2d
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  google_generative_ai: ^0.4.6

  flutter_svg: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/app/logo.png
    - assets/app/menu.jpg
    - assets/app/dietas.png
    - assets/app/ejercicios.jpg

  uses-material-design: true

