name: risk2d
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.29.0
  firebase_auth: ^4.11.2
  cloud_firestore: ^4.15.1
  firebase_ui_auth: ^1.3.0

  flutter_svg: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/app/logo.png


  uses-material-design: true

